"""Core interface labels in the six official languages of the UN."""

LANGUAGES = {
    "English": "en",
    "العربية": "ar",
    "中文": "zh",
    "Français": "fr",
    "Русский": "ru",
    "Español": "es",
}

TEXT = {
    "en": {
        "nav": "Explore", "map": "Field map", "planner": "Planting plan", "doctor": "Plant doctor",
        "history": "My history", "impact": "Impact & policies", "share": "Share app", "account": "Account",
        "language": "Language", "offline": "Offline mode", "tagline": "A practical guide to healthier, more productive fields",
        "problem": "Good land decisions should not depend on guesswork or an expensive plant doctor.",
        "map_title": "Understand your field", "map_intro": "Choose a point to review climate and soil signals, then compare crops against transparent ranges.",
        "planner_title": "Plan crops to grow together", "planner_intro": "Explore locally screened companion crops and see why each pairing may fit.",
        "doctor_title": "Check a leaf", "doctor_intro": "Take or upload a clear leaf photo for a first-pass disease screening and practical next steps.",
        "history_title": "Your saved field history", "history_intro": "Review your past suitability checks and plant health screenings.",
        "impact_title": "Project goals and policies", "sdg_title": "Relevant UN Sustainable Development Goals",
        "privacy_title": "Privacy policy", "terms_title": "Terms of use", "share_title": "Open Terrasense on another device",
        "username": "Username", "password": "Password", "sign_in": "Sign in", "register": "Create account", "logout": "Sign out",
        "guest": "Continue as guest", "analyze": "Analyze field", "find_crops": "Find suitable crops", "analyze_leaf": "Screen this leaf",
        "upload": "Upload a leaf photo", "temperature": "Average temperature", "rainfall": "Annual rainfall", "soil_ph": "Soil pH",
        "select_crop": "Choose a main crop", "offline_note": "Offline mode uses saved local data or values you enter. First-time setup and live data refresh need internet.",
        "online_note": "Live climate and soil lookups use free public services and need an internet connection.",
        "no_history": "No saved activity yet. Sign in to save future checks on this installation.",
        "screening_warning": "This is an early screening aid, not a diagnosis or yield guarantee. Confirm important decisions with local agricultural guidance.",
        "qr_missing": "Set the public app URL in APP_PUBLIC_URL to create a QR code that opens this deployment.",
        "treatment_title": "Low-cost first steps", "language_note": "Core navigation and guidance are available in six UN languages; crop names and some source data remain in their published language.",
        "public_url": "Public app URL", "download_qr": "Download QR code", "scan_qr": "Scan this code to open Terrasense", "camera_photo": "Take a leaf photo", "camera_toggle": "Use camera for a photo",
    },
    "ar": {
        "nav": "استكشف", "map": "خريطة الحقل", "planner": "خطة الزراعة", "doctor": "طبيب النبات",
        "history": "سجلي", "impact": "الأثر والسياسات", "share": "مشاركة التطبيق", "account": "الحساب",
        "language": "اللغة", "offline": "وضع عدم الاتصال", "tagline": "دليل عملي لحقول أكثر صحة وإنتاجية",
        "problem": "ينبغي ألا تعتمد قرارات استخدام الأرض على التخمين أو على طبيب نبات مكلف.",
        "map_title": "افهم حقلك", "map_intro": "اختر موقعاً لمراجعة مؤشرات المناخ والتربة، ثم قارن المحاصيل بنطاقات واضحة.",
        "planner_title": "خطط للمحاصيل التي تنمو معاً", "planner_intro": "استكشف محاصيل مصاحبة مناسبة مبدئياً للموقع واعرف سبب كل اقتراح.",
        "doctor_title": "افحص ورقة نبات", "doctor_intro": "التقط صورة واضحة أو ارفعها للحصول على فحص أولي وإرشادات عملية.",
        "history_title": "سجل الحقول المحفوظ", "history_intro": "راجع فحوص الملاءمة السابقة وفحوص صحة النباتات.",
        "impact_title": "أهداف المشروع والسياسات", "sdg_title": "أهداف الأمم المتحدة للتنمية المستدامة ذات الصلة",
        "privacy_title": "سياسة الخصوصية", "terms_title": "شروط الاستخدام", "share_title": "افتح Terrasense على جهاز آخر",
        "username": "اسم المستخدم", "password": "كلمة المرور", "sign_in": "تسجيل الدخول", "register": "إنشاء حساب", "logout": "تسجيل الخروج",
        "guest": "المتابعة كضيف", "analyze": "حلل الحقل", "find_crops": "اعثر على محاصيل مناسبة", "analyze_leaf": "افحص هذه الورقة",
        "upload": "ارفع صورة ورقة نبات", "temperature": "متوسط الحرارة", "rainfall": "الأمطار السنوية", "soil_ph": "درجة حموضة التربة",
        "select_crop": "اختر المحصول الرئيسي", "offline_note": "يستخدم وضع عدم الاتصال البيانات المحلية المحفوظة أو القيم التي تدخلها. يحتاج الإعداد الأولي وتحديث البيانات المباشرة إلى الإنترنت.",
        "online_note": "تستخدم بيانات المناخ والتربة المباشرة خدمات عامة مجانية وتتطلب اتصالاً بالإنترنت.",
        "no_history": "لا يوجد نشاط محفوظ بعد. سجّل الدخول لحفظ الفحوص المستقبلية على هذا التثبيت.",
        "screening_warning": "هذه أداة فحص أولي وليست تشخيصاً أو ضماناً للمحصول. استشر الإرشاد الزراعي المحلي للقرارات المهمة.",
        "qr_missing": "أضف رابط التطبيق العام في APP_PUBLIC_URL لإنشاء رمز يفتح هذا النشر.",
        "treatment_title": "خطوات أولية منخفضة التكلفة", "language_note": "التنقل والإرشادات الأساسية متاحة بست لغات أممية؛ تبقى أسماء المحاصيل وبعض البيانات بلغتها المنشورة.",
        "public_url": "رابط التطبيق العام", "download_qr": "تنزيل رمز الاستجابة السريعة", "scan_qr": "امسح الرمز لفتح Terrasense", "camera_photo": "التقط صورة للورقة", "camera_toggle": "استخدم الكاميرا لالتقاط صورة",
    },
    "zh": {
        "nav": "功能", "map": "田地地图", "planner": "种植计划", "doctor": "植物医生",
        "history": "使用记录", "impact": "影响与政策", "share": "分享应用", "account": "账户",
        "language": "语言", "offline": "离线模式", "tagline": "帮助农田更健康、更高效的实用指南",
        "problem": "土地决策不应依赖猜测，也不应必须求助昂贵的植物医生。",
        "map_title": "了解您的田地", "map_intro": "选择位置查看气候和土壤指标，再根据透明的范围比较作物。",
        "planner_title": "规划适合共同种植的作物", "planner_intro": "查看适合该地点的伴生作物建议及其原因。",
        "doctor_title": "检查叶片", "doctor_intro": "上传清晰的叶片照片，进行初步病害筛查并获取实用建议。",
        "history_title": "已保存的田地记录", "history_intro": "查看以前的适宜性分析和植物健康筛查。",
        "impact_title": "项目目标与政策", "sdg_title": "相关联合国可持续发展目标",
        "privacy_title": "隐私政策", "terms_title": "使用条款", "share_title": "在其他设备上打开 Terrasense",
        "username": "用户名", "password": "密码", "sign_in": "登录", "register": "创建账户", "logout": "退出登录",
        "guest": "以访客身份继续", "analyze": "分析田地", "find_crops": "查找适宜作物", "analyze_leaf": "筛查此叶片",
        "upload": "上传叶片照片", "temperature": "平均气温", "rainfall": "年降雨量", "soil_ph": "土壤酸碱度",
        "select_crop": "选择主要作物", "offline_note": "离线模式使用本地保存的数据或您输入的数值。首次设置和实时数据更新需要互联网。",
        "online_note": "实时气候和土壤数据来自免费的公共服务，需要互联网连接。", "no_history": "暂无保存记录。登录后可在此安装中保存后续检查。",
        "screening_warning": "此工具仅用于初步筛查，不构成诊断或产量保证。重要决策请咨询当地农业指导机构。",
        "qr_missing": "请在 APP_PUBLIC_URL 中设置公开应用网址，以生成可打开此部署的二维码。",
        "treatment_title": "低成本初步措施", "language_note": "核心导航与指南支持联合国六种官方语言；作物名称和部分来源数据保留其发布语言。",
        "public_url": "应用公开网址", "download_qr": "下载二维码", "scan_qr": "扫描此码以打开 Terrasense", "camera_photo": "拍摄叶片照片", "camera_toggle": "使用相机拍照",
    },
    "fr": {
        "nav": "Explorer", "map": "Carte du champ", "planner": "Plan de plantation", "doctor": "Santé des plantes",
        "history": "Mon historique", "impact": "Impact et politiques", "share": "Partager l’application", "account": "Compte",
        "language": "Langue", "offline": "Mode hors ligne", "tagline": "Un guide pratique pour des champs plus sains et productifs",
        "problem": "Les décisions foncières ne devraient pas dépendre du hasard ou d’un spécialiste coûteux.",
        "map_title": "Comprendre votre champ", "map_intro": "Choisissez un point pour consulter le climat et le sol, puis comparez les cultures selon des seuils transparents.",
        "planner_title": "Planifier des cultures associées", "planner_intro": "Découvrez des associations adaptées au site et les raisons de chaque suggestion.",
        "doctor_title": "Examiner une feuille", "doctor_intro": "Importez une photo nette pour un premier dépistage et des conseils pratiques.",
        "history_title": "Historique de vos champs", "history_intro": "Consultez vos analyses de culture et dépistages précédents.",
        "impact_title": "Objectifs et politiques du projet", "sdg_title": "Objectifs de développement durable concernés",
        "privacy_title": "Politique de confidentialité", "terms_title": "Conditions d’utilisation", "share_title": "Ouvrir Terrasense sur un autre appareil",
        "username": "Nom d’utilisateur", "password": "Mot de passe", "sign_in": "Connexion", "register": "Créer un compte", "logout": "Déconnexion",
        "guest": "Continuer comme invité", "analyze": "Analyser le champ", "find_crops": "Trouver des cultures adaptées", "analyze_leaf": "Examiner cette feuille",
        "upload": "Importer une photo de feuille", "temperature": "Température moyenne", "rainfall": "Pluviométrie annuelle", "soil_ph": "pH du sol",
        "select_crop": "Choisir une culture principale", "offline_note": "Le mode hors ligne utilise les données locales ou les valeurs saisies. La première installation et l’actualisation des données nécessitent Internet.",
        "online_note": "Les données climatiques et pédologiques en direct proviennent de services publics gratuits et nécessitent Internet.",
        "no_history": "Aucune activité enregistrée. Connectez-vous pour enregistrer les prochains contrôles sur cette installation.",
        "screening_warning": "Cet outil fournit un premier dépistage, pas un diagnostic ni une garantie de rendement. Demandez conseil aux services agricoles locaux pour les décisions importantes.",
        "qr_missing": "Définissez l’URL publique dans APP_PUBLIC_URL pour créer un QR code ouvrant ce déploiement.",
        "treatment_title": "Premiers gestes à faible coût", "language_note": "La navigation et les conseils principaux sont disponibles dans les six langues officielles de l’ONU; les noms de cultures et certaines données gardent leur langue source.",
        "public_url": "URL publique de l’application", "download_qr": "Télécharger le QR code", "scan_qr": "Scannez ce code pour ouvrir Terrasense", "camera_photo": "Prendre une photo de feuille", "camera_toggle": "Utiliser l’appareil photo",
    },
    "ru": {
        "nav": "Разделы", "map": "Карта поля", "planner": "План посадок", "doctor": "Помощник по растениям",
        "history": "История", "impact": "Влияние и правила", "share": "Поделиться приложением", "account": "Учётная запись",
        "language": "Язык", "offline": "Автономный режим", "tagline": "Практический помощник для здоровых и продуктивных полей",
        "problem": "Решения об использовании земли не должны зависеть от догадок или дорогого специалиста.",
        "map_title": "Изучите своё поле", "map_intro": "Выберите точку, чтобы посмотреть климат и почву, затем сравните культуры по понятным диапазонам.",
        "planner_title": "План совместных посадок", "planner_intro": "Посмотрите на подходящие для участка культуры-компаньоны и причины рекомендации.",
        "doctor_title": "Проверка листа", "doctor_intro": "Загрузите чёткое фото листа для первичной оценки болезни и практических советов.",
        "history_title": "История поля", "history_intro": "Просмотрите предыдущие оценки пригодности и проверки здоровья растений.",
        "impact_title": "Цели проекта и правила", "sdg_title": "Связанные Цели устойчивого развития ООН",
        "privacy_title": "Политика конфиденциальности", "terms_title": "Условия использования", "share_title": "Откройте Terrasense на другом устройстве",
        "username": "Имя пользователя", "password": "Пароль", "sign_in": "Войти", "register": "Создать аккаунт", "logout": "Выйти",
        "guest": "Продолжить как гость", "analyze": "Анализ поля", "find_crops": "Подобрать культуры", "analyze_leaf": "Проверить лист",
        "upload": "Загрузить фото листа", "temperature": "Средняя температура", "rainfall": "Годовые осадки", "soil_ph": "Кислотность почвы",
        "select_crop": "Выберите основную культуру", "offline_note": "Автономный режим использует сохранённые локальные данные или введённые вами значения. Первичная настройка и обновление данных требуют интернета.",
        "online_note": "Актуальные климатические и почвенные данные поступают из бесплатных открытых сервисов и требуют подключения к интернету.",
        "no_history": "Сохранённых действий пока нет. Войдите, чтобы сохранять будущие проверки в этой установке.",
        "screening_warning": "Это предварительная оценка, а не диагноз и не гарантия урожая. Важные решения обсудите с местной аграрной службой.",
        "qr_missing": "Укажите общедоступный адрес приложения в APP_PUBLIC_URL, чтобы создать QR-код для этой версии.",
        "treatment_title": "Недорогие первые меры", "language_note": "Основная навигация и рекомендации доступны на шести официальных языках ООН; названия культур и часть исходных данных сохраняют язык публикации.",
        "public_url": "Общедоступный адрес приложения", "download_qr": "Скачать QR-код", "scan_qr": "Отсканируйте код, чтобы открыть Terrasense", "camera_photo": "Сфотографировать лист", "camera_toggle": "Включить камеру для фото",
    },
    "es": {
        "nav": "Explorar", "map": "Mapa del campo", "planner": "Plan de siembra", "doctor": "Salud de las plantas",
        "history": "Mi historial", "impact": "Impacto y políticas", "share": "Compartir la aplicación", "account": "Cuenta",
        "language": "Idioma", "offline": "Modo sin conexión", "tagline": "Una guía práctica para campos más sanos y productivos",
        "problem": "Las decisiones sobre la tierra no deberían depender de conjeturas ni de un especialista costoso.",
        "map_title": "Conoce tu campo", "map_intro": "Elige un punto para consultar el clima y el suelo; compara cultivos con rangos transparentes.",
        "planner_title": "Planifica cultivos asociados", "planner_intro": "Explora cultivos compañeros adecuados para el sitio y conoce por qué se sugieren.",
        "doctor_title": "Revisa una hoja", "doctor_intro": "Sube una foto clara para obtener una detección inicial y pasos prácticos.",
        "history_title": "Historial de tu campo", "history_intro": "Consulta tus evaluaciones de cultivo y revisiones de salud anteriores.",
        "impact_title": "Objetivos y políticas del proyecto", "sdg_title": "Objetivos de Desarrollo Sostenible relacionados",
        "privacy_title": "Política de privacidad", "terms_title": "Términos de uso", "share_title": "Abre Terrasense en otro dispositivo",
        "username": "Nombre de usuario", "password": "Contraseña", "sign_in": "Iniciar sesión", "register": "Crear cuenta", "logout": "Cerrar sesión",
        "guest": "Continuar como invitado", "analyze": "Analizar campo", "find_crops": "Buscar cultivos adecuados", "analyze_leaf": "Revisar esta hoja",
        "upload": "Subir una foto de hoja", "temperature": "Temperatura media", "rainfall": "Lluvia anual", "soil_ph": "pH del suelo",
        "select_crop": "Elige un cultivo principal", "offline_note": "El modo sin conexión usa datos locales guardados o valores que introduces. La configuración inicial y las actualizaciones requieren internet.",
        "online_note": "Las consultas climáticas y del suelo usan servicios públicos gratuitos y requieren conexión a internet.",
        "no_history": "Todavía no hay actividad guardada. Inicia sesión para guardar futuras consultas en esta instalación.",
        "screening_warning": "Es una herramienta de detección inicial, no un diagnóstico ni una garantía de rendimiento. Consulta asesoría agrícola local para decisiones importantes.",
        "qr_missing": "Configura la URL pública en APP_PUBLIC_URL para crear un código QR que abra esta instalación.",
        "treatment_title": "Primeros pasos de bajo costo", "language_note": "La navegación y la guía principal están disponibles en los seis idiomas oficiales de la ONU; algunos nombres de cultivos y datos conservan su idioma original.",
        "public_url": "URL pública de la aplicación", "download_qr": "Descargar código QR", "scan_qr": "Escanea este código para abrir Terrasense", "camera_photo": "Tomar una foto de la hoja", "camera_toggle": "Usar la cámara para tomar una foto",
    },
}

VOICE_TEXT = {
    "en": {
        "read_aloud": "Read this guidance aloud", "stop_reading": "Stop reading",
        "voice_unavailable": "A voice for this language is not available in your browser.",
        "copy_link": "Copy link", "link_copied": "Link copied", "copy_failed": "Could not copy the link.",
        "share_description": "Scan the QR code or copy this page’s link to open Terrasense on another device.",
        "point_instruction": "Select a point on the map to begin.", "point_selected": "Selected point: {lat}, {lon}.",
        "field_unknown": "There is not enough climate or soil information to assess {crop}. Add local values or reconnect to refresh the data.",
        "field_suitable": "The available climate and soil signals are broadly within the screening ranges for {crop}. The screening score is {score} percent. Check local planting dates, water, and field conditions.",
        "field_marginal": "Some available conditions fit {crop}, while others fall outside its preferred ranges. The screening score is {score} percent. Review local conditions before deciding.",
        "field_unsuitable": "The available field indicators fall outside the screening ranges for {crop}. The screening score is {score} percent. Compare other crops and confirm local conditions before deciding.",
        "degrees_celsius": "degrees Celsius", "millimeters_per_year": "millimeters per year", "elevation": "Terrain elevation", "meters": "meters", "slope": "Nearby slope estimate",
        "top_crops": "Highest-scoring screened crops", "companion_plan": "Companion planting plan for {crop}.", "companion_crops": "Suggested companion crops: {crops}.",
        "disease_result": "The model’s closest trained class is {disease} on {plant}. Its overall model score is {score} percent. This is an early screening result, not a confirmed diagnosis.",
        "disease_uncertain": "The crop was not selected. This is only the model’s closest trained class, {disease} on {plant}, and may not match the plant in the photo.",
        "disease_unknown": "The model could not identify a trained plant or disease class. Try a clear leaf photo or ask local agricultural support.",
        "unsupported_crop": "This model does not cover {plant}, so it cannot screen this crop reliably. Supported classes include {supported}. No disease label was assigned.",
        "disease_next_steps": "Review the low-cost first steps shown on screen and confirm treatment with local agricultural guidance.",
        "activity_field": "Field suitability", "activity_crops": "Crop finder", "activity_leaf": "Leaf screening",
        "history_login": "Sign in from the sidebar to view saved activity. Guest activity is available only in this session.",
        "impact_voice": "Terrasense helps farmers compare field conditions, crop options, and first steps for leaf symptoms.",
    },
    "ar": {
        "read_aloud": "استمع إلى هذه الإرشادات", "stop_reading": "إيقاف القراءة",
        "voice_unavailable": "لا يتوفر صوت بهذه اللغة في المتصفح.",
        "copy_link": "نسخ الرابط", "link_copied": "تم نسخ الرابط", "copy_failed": "تعذر نسخ الرابط.",
        "share_description": "امسح رمز الاستجابة السريعة أو انسخ رابط الصفحة لفتح Terrasense على جهاز آخر.",
        "point_instruction": "اختر نقطة على الخريطة للبدء.", "point_selected": "النقطة المحددة: {lat}، {lon}.",
        "field_unknown": "لا تتوفر معلومات كافية عن المناخ أو التربة لتقييم {crop}. أضف قيماً محلية أو اتصل بالإنترنت لتحديث البيانات.",
        "field_suitable": "تقع مؤشرات المناخ والتربة المتاحة عموماً ضمن نطاقات الفحص المناسبة لـ {crop}. درجة الفحص {score} بالمئة. راجع مواعيد الزراعة والمياه وظروف الحقل المحلية.",
        "field_marginal": "تلائم بعض الظروف المتاحة {crop} بينما تقع ظروف أخرى خارج نطاقاته المفضلة. درجة الفحص {score} بالمئة. راجع الظروف المحلية قبل اتخاذ القرار.",
        "field_unsuitable": "تقع مؤشرات الحقل المتاحة خارج نطاقات الفحص المناسبة لـ {crop}. درجة الفحص {score} بالمئة. قارن محاصيل أخرى وتحقق من الظروف المحلية قبل القرار.",
        "degrees_celsius": "درجة مئوية", "millimeters_per_year": "ملليمتر سنوياً", "elevation": "ارتفاع التضاريس", "meters": "أمتار", "slope": "تقدير انحدار المنطقة المجاورة",
        "top_crops": "أعلى المحاصيل في الفحص", "companion_plan": "خطة الزراعة المصاحبة لـ {crop}.", "companion_crops": "المحاصيل المصاحبة المقترحة: {crops}.",
        "disease_result": "أقرب فئة تعلمها النموذج هي {disease} على {plant}. درجة النموذج الإجمالية {score} بالمئة. هذه نتيجة فحص أولي وليست تشخيصاً مؤكداً.",
        "disease_uncertain": "لم يتم اختيار المحصول. هذه أقرب فئة تعلمها النموذج، {disease} على {plant}، وقد لا تطابق النبات في الصورة.",
        "disease_unknown": "تعذر على النموذج تحديد فئة نبات أو مرض تعلمها. جرّب صورة واضحة للورقة أو استشر الإرشاد الزراعي المحلي.",
        "unsupported_crop": "هذا النموذج لا يشمل {plant}، لذلك لا يمكنه فحص هذا المحصول بدقة. تشمل الفئات المدعومة {supported}. لم يتم تعيين مرض.",
        "disease_next_steps": "راجع الخطوات الأولية منخفضة التكلفة الظاهرة على الشاشة وتحقق من العلاج مع الإرشاد الزراعي المحلي.",
        "activity_field": "ملاءمة الحقل", "activity_crops": "البحث عن المحاصيل", "activity_leaf": "فحص الورقة",
        "history_login": "سجّل الدخول من الشريط الجانبي لعرض النشاط المحفوظ. يتوفر نشاط الضيف في هذه الجلسة فقط.",
        "impact_voice": "يساعد Terrasense المزارعين على مقارنة ظروف الحقل وخيارات المحاصيل والخطوات الأولية لأعراض الأوراق.",
    },
    "zh": {
        "read_aloud": "朗读这些指南", "stop_reading": "停止朗读",
        "voice_unavailable": "浏览器没有可用的此语言语音。",
        "copy_link": "复制链接", "link_copied": "链接已复制", "copy_failed": "无法复制链接。",
        "share_description": "扫描二维码或复制此页面链接，在其他设备上打开 Terrasense。",
        "point_instruction": "在地图上选择一个位置以开始。", "point_selected": "已选位置：{lat}，{lon}。",
        "field_unknown": "气候或土壤信息不足，无法评估 {crop}。请填写本地数据或联网刷新数据。",
        "field_suitable": "现有气候和土壤指标大致符合 {crop} 的筛查范围。筛查得分为 {score}%。种植前请核实当地种植日期、水源和田间条件。",
        "field_marginal": "部分现有条件适合 {crop}，另一些则超出其偏好范围。筛查得分为 {score}%。请先核实当地条件。",
        "field_unsuitable": "现有田间指标超出 {crop} 的筛查范围。筛查得分为 {score}%。请比较其他作物并核实当地条件。",
        "degrees_celsius": "摄氏度", "millimeters_per_year": "毫米每年", "elevation": "地形海拔", "meters": "米", "slope": "附近坡度估算",
        "top_crops": "筛查得分最高的作物", "companion_plan": "{crop} 的伴生种植计划。", "companion_crops": "建议的伴生作物：{crops}。",
        "disease_result": "模型最接近的已训练类别是 {plant} 的 {disease}。模型总体得分为 {score}%。这只是初步筛查结果，不是确诊。",
        "disease_uncertain": "尚未选择作物。模型最接近的已训练类别是 {plant} 的 {disease}，可能与照片中的植物不符。",
        "disease_unknown": "模型无法识别已训练的植物或病害类别。请尝试清晰的叶片照片或咨询当地农业支持人员。",
        "unsupported_crop": "模型不包含 {plant}，因此无法可靠筛查此作物。支持的类别包括 {supported}。未指定病害。",
        "disease_next_steps": "请查看屏幕上的低成本初步措施，并向当地农业指导人员确认处理方法。",
        "activity_field": "田地适宜性", "activity_crops": "作物查找", "activity_leaf": "叶片筛查",
        "history_login": "请从侧边栏登录以查看已保存的活动。访客活动仅在本次会话中保留。",
        "impact_voice": "Terrasense 帮助农民比较田间条件、作物选择和叶片症状的初步处理步骤。",
    },
    "fr": {
        "read_aloud": "Lire ces conseils à voix haute", "stop_reading": "Arrêter la lecture",
        "voice_unavailable": "Aucune voix pour cette langue n’est disponible dans votre navigateur.",
        "copy_link": "Copier le lien", "link_copied": "Lien copié", "copy_failed": "Impossible de copier le lien.",
        "share_description": "Scannez le QR code ou copiez le lien de cette page pour ouvrir Terrasense sur un autre appareil.",
        "point_instruction": "Choisissez un point sur la carte pour commencer.", "point_selected": "Point sélectionné : {lat}, {lon}.",
        "field_unknown": "Les données climatiques ou pédologiques sont insuffisantes pour évaluer {crop}. Saisissez des valeurs locales ou reconnectez-vous pour actualiser les données.",
        "field_suitable": "Les indicateurs climatiques et pédologiques disponibles correspondent globalement aux plages de dépistage pour {crop}. Le score est de {score} pour cent. Vérifiez les dates de plantation, l’eau et les conditions locales.",
        "field_marginal": "Certaines conditions conviennent à {crop}, tandis que d’autres sortent des plages préférées. Le score est de {score} pour cent. Vérifiez les conditions locales avant de décider.",
        "field_unsuitable": "Les indicateurs disponibles sortent des plages de dépistage pour {crop}. Le score est de {score} pour cent. Comparez d’autres cultures et vérifiez les conditions locales.",
        "degrees_celsius": "degrés Celsius", "millimeters_per_year": "millimètres par an", "elevation": "Altitude du terrain", "meters": "mètres", "slope": "Estimation de la pente voisine",
        "top_crops": "Cultures les mieux classées", "companion_plan": "Plan de cultures associées pour {crop}.", "companion_crops": "Cultures associées suggérées : {crops}.",
        "disease_result": "La classe apprise la plus proche est {disease} sur {plant}. Le score global du modèle est de {score} pour cent. Il s’agit d’un dépistage préliminaire, pas d’un diagnostic confirmé.",
        "disease_uncertain": "La culture n’a pas été choisie. La classe apprise la plus proche est {disease} sur {plant}, mais elle peut ne pas correspondre à la plante de la photo.",
        "disease_unknown": "Le modèle n’a pas reconnu de classe de plante ou de maladie apprise. Essayez une photo nette ou demandez conseil aux services agricoles locaux.",
        "unsupported_crop": "Ce modèle ne couvre pas {plant} et ne peut donc pas examiner cette culture de façon fiable. Les classes prises en charge comprennent {supported}. Aucune maladie n’a été attribuée.",
        "disease_next_steps": "Consultez les premières mesures peu coûteuses affichées et confirmez le traitement auprès des services agricoles locaux.",
        "activity_field": "Adéquation du champ", "activity_crops": "Recherche de cultures", "activity_leaf": "Dépistage de feuille",
        "history_login": "Connectez-vous dans la barre latérale pour consulter l’activité enregistrée. L’activité invitée reste limitée à cette session.",
        "impact_voice": "Terrasense aide les agriculteurs à comparer les conditions du champ, les cultures possibles et les premières mesures pour les symptômes des feuilles.",
    },
    "ru": {
        "read_aloud": "Прочитать рекомендации вслух", "stop_reading": "Остановить чтение",
        "voice_unavailable": "В браузере нет доступного голоса для этого языка.",
        "copy_link": "Скопировать ссылку", "link_copied": "Ссылка скопирована", "copy_failed": "Не удалось скопировать ссылку.",
        "share_description": "Отсканируйте QR-код или скопируйте ссылку этой страницы, чтобы открыть Terrasense на другом устройстве.",
        "point_instruction": "Выберите точку на карте, чтобы начать.", "point_selected": "Выбранная точка: {lat}, {lon}.",
        "field_unknown": "Недостаточно климатических данных или данных о почве для оценки {crop}. Введите местные значения или подключитесь к сети для обновления данных.",
        "field_suitable": "Доступные климатические и почвенные показатели в целом соответствуют диапазонам проверки для культуры {crop}. Оценка — {score} процентов. Проверьте местные сроки посадки, воду и условия поля.",
        "field_marginal": "Некоторые доступные условия подходят для {crop}, а другие выходят за предпочтительные диапазоны. Оценка — {score} процентов. Проверьте местные условия перед решением.",
        "field_unsuitable": "Доступные показатели поля выходят за диапазоны проверки для {crop}. Оценка — {score} процентов. Сравните другие культуры и проверьте местные условия.",
        "degrees_celsius": "градусов Цельсия", "millimeters_per_year": "миллиметров в год", "elevation": "Высота местности", "meters": "метров", "slope": "Оценка уклона поблизости",
        "top_crops": "Культуры с лучшими результатами проверки", "companion_plan": "План совместных посадок для культуры {crop}.", "companion_crops": "Рекомендуемые культуры-компаньоны: {crops}.",
        "disease_result": "Ближайший обученный класс модели — {disease} на растении {plant}. Общая оценка модели — {score} процентов. Это предварительная проверка, а не подтверждённый диагноз.",
        "disease_uncertain": "Культура не выбрана. Ближайший обученный класс модели — {disease} на растении {plant}; он может не соответствовать растению на фото.",
        "disease_unknown": "Модель не распознала обученный класс растения или болезни. Попробуйте чёткое фото листа или обратитесь в местную аграрную службу.",
        "unsupported_crop": "Модель не обучена на культуре {plant} и не может надёжно её проверить. Поддерживаемые классы включают {supported}. Болезнь не назначена.",
        "disease_next_steps": "Посмотрите первые недорогие меры на экране и уточните лечение в местной аграрной службе.",
        "activity_field": "Пригодность поля", "activity_crops": "Подбор культур", "activity_leaf": "Проверка листа",
        "history_login": "Войдите через боковую панель, чтобы просмотреть сохранённые действия. Гостевые действия доступны только в этой сессии.",
        "impact_voice": "Terrasense помогает фермерам сравнивать условия поля, варианты культур и первые меры при симптомах на листьях.",
    },
    "es": {
        "read_aloud": "Leer estas indicaciones en voz alta", "stop_reading": "Detener lectura",
        "voice_unavailable": "Tu navegador no tiene una voz disponible para este idioma.",
        "copy_link": "Copiar enlace", "link_copied": "Enlace copiado", "copy_failed": "No se pudo copiar el enlace.",
        "share_description": "Escanea el código QR o copia el enlace de esta página para abrir Terrasense en otro dispositivo.",
        "point_instruction": "Selecciona un punto en el mapa para empezar.", "point_selected": "Punto seleccionado: {lat}, {lon}.",
        "field_unknown": "No hay suficientes datos de clima o suelo para evaluar {crop}. Añade valores locales o vuelve a conectarte para actualizar los datos.",
        "field_suitable": "Los indicadores disponibles de clima y suelo se encuentran, en general, dentro de los rangos de evaluación para {crop}. La puntuación es {score} por ciento. Comprueba las fechas de siembra, el agua y las condiciones locales.",
        "field_marginal": "Algunas condiciones disponibles favorecen {crop}, pero otras quedan fuera de sus rangos preferidos. La puntuación es {score} por ciento. Revisa las condiciones locales antes de decidir.",
        "field_unsuitable": "Los indicadores disponibles del campo quedan fuera de los rangos de evaluación para {crop}. La puntuación es {score} por ciento. Compara otros cultivos y verifica las condiciones locales.",
        "degrees_celsius": "grados Celsius", "millimeters_per_year": "milímetros al año", "elevation": "Elevación del terreno", "meters": "metros", "slope": "Estimación de la pendiente cercana",
        "top_crops": "Cultivos con mejor resultado de evaluación", "companion_plan": "Plan de cultivos asociados para {crop}.", "companion_crops": "Cultivos asociados sugeridos: {crops}.",
        "disease_result": "La clase aprendida más cercana es {disease} en {plant}. La puntuación general del modelo es {score} por ciento. Es una evaluación inicial, no un diagnóstico confirmado.",
        "disease_uncertain": "No se eligió el cultivo. La clase aprendida más cercana es {disease} en {plant}, y puede no corresponder a la planta de la foto.",
        "disease_unknown": "El modelo no identificó una clase de planta o enfermedad aprendida. Prueba con una foto clara de la hoja o consulta asesoría agrícola local.",
        "unsupported_crop": "Este modelo no incluye {plant}, así que no puede evaluar este cultivo de forma fiable. Las clases compatibles incluyen {supported}. No se asignó ninguna enfermedad.",
        "disease_next_steps": "Revisa los primeros pasos de bajo costo que aparecen en pantalla y confirma el tratamiento con asesoría agrícola local.",
        "activity_field": "Idoneidad del campo", "activity_crops": "Búsqueda de cultivos", "activity_leaf": "Revisión de hoja",
        "history_login": "Inicia sesión desde la barra lateral para ver la actividad guardada. La actividad de invitado solo está disponible en esta sesión.",
        "impact_voice": "Terrasense ayuda a los agricultores a comparar las condiciones del campo, las opciones de cultivo y los primeros pasos ante síntomas en las hojas.",
    },
}

EXTRA_TEXT = {
    "en": {
        "privacy_body": "Draft for project review. The browser asks permission to read your device location for the map; you can deny it. Field coordinates go to NASA POWER, SoilGrids/ISRIC, and Open-Meteo only when online checks are run; map tile requests go to OpenStreetMap. The app uses local account names and salted password hashes to link saved activity. A leaf photo uploaded to a hosted app reaches the app server for inference and is not saved to the app database. The local SQLite database stores account IDs, local password hashes, saved checks, and cached field values. Hosted deployments need persistent, access-controlled storage.",
        "terms_body": "Draft for project review. Crop ranges, companion suggestions, and image predictions are general screening aids. They are not professional diagnosis, treatment instructions, or yield forecasts. Confirm important decisions with local agricultural guidance and check applicable rules before applying treatments. The user remains responsible for field decisions.",
        "sdg_note": "These are intended areas of contribution, not an official UN endorsement or measured impact claim.",
        "offline_detail": "The app uses free public datasets and open-source libraries without paid API keys. Saved point data and manually entered values can be used offline. Live map tiles and climate, soil, and elevation refreshes need internet. Download the disease model once before offline screening. A disconnected first-time setup requires preloading the model and field data.",
    },
    "ar": {
        "privacy_body": "مسودة لمراجعة المشروع. يطلب المتصفح الإذن لاستخدام موقع جهازك على الخريطة ويمكنك الرفض. تُرسل إحداثيات الحقل إلى NASA POWER وSoilGrids/ISRIC وOpen-Meteo عند إجراء الفحوص المباشرة فقط، وتُرسل طلبات الخرائط إلى OpenStreetMap. يستخدم التطبيق أسماء الحسابات المحلية وتجزئات كلمات المرور المملحة لربط النشاط المحفوظ. تصل صورة الورقة في التطبيق المستضاف إلى خادم التحليل ولا تُحفظ في قاعدة البيانات. تخزن SQLite معرّفات الحسابات وكلمات المرور المحلية المحمية والفحوص والقيم المؤقتة. يحتاج النشر المستضاف إلى تخزين دائم ومقيد الوصول.",
        "terms_body": "مسودة لمراجعة المشروع. نطاقات المحاصيل واقتراحات الزراعة المصاحبة وتنبؤات الصور أدوات فحص عامة، وليست تشخيصاً مهنياً أو تعليمات علاج أو توقعاً للمحصول. راجع الإرشاد الزراعي المحلي والقواعد المعمول بها قبل القرارات المهمة أو استخدام أي علاج. يبقى المستخدم مسؤولاً عن قرارات الحقل.",
        "sdg_note": "هذه مجالات إسهام مقصودة وليست اعتماداً رسمياً من الأمم المتحدة أو ادعاءً بأثر مقاس.",
        "offline_detail": "يستخدم التطبيق بيانات عامة مجانية ومكتبات مفتوحة المصدر دون مفاتيح API مدفوعة. يمكن استخدام بيانات الموقع المحفوظة والقيم المدخلة يدوياً دون اتصال. تحتاج الخرائط المباشرة وتحديثات المناخ والتربة والارتفاع إلى الإنترنت. نزّل نموذج المرض مرة قبل الفحص دون اتصال، وحمّل النموذج وبيانات الحقل مسبقاً للإعداد الأولي المنقطع.",
    },
    "zh": {
        "privacy_body": "项目审阅稿。浏览器会请求使用设备位置来定位地图，您可以拒绝。只有运行在线检查时，田地坐标才会发送至 NASA POWER、SoilGrids/ISRIC 和 Open-Meteo；地图请求会发送至 OpenStreetMap。应用使用本地账户名和加盐密码哈希关联保存的记录。托管应用中的叶片照片会到达应用服务器进行分析，不会保存到应用数据库。本地 SQLite 数据库存储账户编号、本地密码哈希、检查记录和缓存田地数据。托管部署需要持久且有访问控制的存储。",
        "terms_body": "项目审阅稿。作物范围、伴生种植建议和图像预测仅供一般筛查，不构成专业诊断、治疗说明或产量预测。重要决策和处理措施请先咨询当地农业指导并核实适用规定。田间决策由用户负责。",
        "sdg_note": "这些是预期贡献领域，不代表联合国官方认可或经测量的影响。",
        "offline_detail": "应用使用免费的公共数据和开源库，无需付费 API 密钥。保存的地点数据和手动输入值可离线使用。实时地图、气候、土壤和海拔更新需要互联网。离线筛查前需下载一次病害模型。首次完全离线使用需要预先准备模型和田地数据。",
    },
    "fr": {
        "privacy_body": "Projet de texte à vérifier. Le navigateur demande l’autorisation d’utiliser la position de l’appareil pour centrer la carte; vous pouvez refuser. Les coordonnées du champ sont envoyées à NASA POWER, SoilGrids/ISRIC et Open-Meteo uniquement lors des contrôles en ligne; les tuiles cartographiques viennent d’OpenStreetMap. L’application utilise des noms de compte locaux et des mots de passe hachés avec un sel pour associer l’historique enregistré. Une photo de feuille importée dans une application hébergée atteint le serveur pour l’analyse et n’est pas enregistrée dans sa base de données. SQLite stocke les identifiants, les empreintes de mots de passe locaux, les contrôles et les valeurs en cache. Un déploiement hébergé doit utiliser un stockage persistant et contrôlé.",
        "terms_body": "Projet de texte à vérifier. Les plages de culture, suggestions d’association et prédictions d’image sont des outils de dépistage général. Elles ne constituent ni un diagnostic professionnel, ni des instructions de traitement, ni une prévision de rendement. Pour toute décision importante, consultez les services agricoles locaux et vérifiez les règles applicables. L’utilisateur reste responsable des décisions au champ.",
        "sdg_note": "Il s’agit de domaines de contribution visés, et non d’une approbation officielle de l’ONU ni d’un impact mesuré.",
        "offline_detail": "L’application utilise des données publiques gratuites et des bibliothèques libres sans clé API payante. Les données de point enregistrées et les valeurs saisies manuellement fonctionnent hors ligne. Les cartes et l’actualisation du climat, du sol et de l’altitude nécessitent Internet. Téléchargez le modèle de maladie une fois avant le dépistage hors ligne. Une première installation sans réseau exige de précharger le modèle et les données du champ.",
    },
    "ru": {
        "privacy_body": "Черновик для проверки проекта. Браузер запросит разрешение на получение местоположения устройства для карты; вы можете отказать. Координаты поля отправляются в NASA POWER, SoilGrids/ISRIC и Open-Meteo только при онлайн-проверке; запросы карт идут в OpenStreetMap. Приложение связывает сохранённую историю с локальными именами аккаунтов и хешами паролей с солью. Фото листа, загруженное в размещённое приложение, поступает на сервер для анализа и не сохраняется в базе. SQLite хранит идентификаторы аккаунтов, хеши локальных паролей, сохранённые проверки и кэшированные данные поля. Для хостинга нужны постоянное хранилище и контроль доступа.",
        "terms_body": "Черновик для проверки проекта. Диапазоны культур, советы по совместным посадкам и прогнозы по изображению служат только для предварительной оценки. Это не профессиональный диагноз, не инструкция по лечению и не прогноз урожая. Важные решения и способы обработки проверяйте у местных аграрных специалистов и по действующим правилам. За решения на поле отвечает пользователь.",
        "sdg_note": "Это предполагаемые направления вклада, а не официальное одобрение ООН или измеренная оценка воздействия.",
        "offline_detail": "Приложение использует бесплатные открытые данные и библиотеки без платных API-ключей. Сохранённые данные точки и введённые вручную значения доступны офлайн. Для обновления карт, климата, почвы и высоты нужен интернет. Перед офлайн-проверкой один раз загрузите модель болезни. Для первой установки без сети заранее загрузите модель и данные поля.",
    },
    "es": {
        "privacy_body": "Borrador para revisión del proyecto. El navegador solicita permiso para usar la ubicación del dispositivo en el mapa; puedes denegarlo. Las coordenadas del campo se envían a NASA POWER, SoilGrids/ISRIC y Open-Meteo solo al realizar análisis en línea; las solicitudes de mapas van a OpenStreetMap. La aplicación vincula el historial guardado con nombres de cuenta locales y hashes de contraseñas con sal. Una foto subida a una aplicación alojada llega al servidor para su análisis y no se guarda en la base de datos. SQLite guarda identificadores de cuenta, hashes de contraseñas locales, revisiones y datos de campo en caché. El alojamiento requiere almacenamiento persistente y control de acceso.",
        "terms_body": "Borrador para revisión del proyecto. Los rangos de cultivo, las sugerencias de asociación y las predicciones de imágenes son herramientas de detección general. No son un diagnóstico profesional, instrucciones de tratamiento ni pronósticos de rendimiento. Consulta asesoría agrícola local y las normas aplicables antes de decisiones importantes o tratamientos. El usuario es responsable de las decisiones en el campo.",
        "sdg_note": "Estas son áreas de contribución previstas, no un respaldo oficial de la ONU ni una afirmación de impacto medido.",
        "offline_detail": "La aplicación usa datos públicos gratuitos y bibliotecas de código abierto sin claves API de pago. Los datos guardados del lugar y los valores manuales se pueden usar sin conexión. Los mapas y las actualizaciones de clima, suelo y elevación requieren internet. Descarga el modelo de enfermedades una vez antes de usarlo sin conexión. La instalación inicial desconectada requiere precargar el modelo y los datos del campo.",
    },
}

ASSISTANT_TEXT = {
    "en": {
        "disease_result": "Within the {plant} labels, the model's closest class is {disease} ({score}). Overall model support for {plant} is {crop_support}. This is a screening result, not a confirmed diagnosis.",
        "disease_weak_support": "The model gives very little overall support to {plant}. Its strongest overall class is {overall_disease} on {overall_plant} ({overall_score}). Within {plant} labels, the top match is {disease} ({score}), but the crop match is too weak to say this leaf is healthy or diseased.",
        "disease_class_score": "Class score within selected crop",
        "disease_crop_support": "Overall model support for crop",
        "disease_score_note": "The class score is ranked within the selected crop's labels. Overall crop support sums those labels across the full model. Neither score is diagnostic certainty.",
        "disease_weak_treatment": "No treatment is suggested because the model did not reliably match the selected crop. Retake a clear photo and ask local agricultural guidance before treating.",
    },
    "ar": {
        "disease_result": "ضمن فئات {plant}، أقرب فئة للنموذج هي {disease} ({score}). دعم النموذج الإجمالي للمحصول هو {crop_support}. هذه نتيجة فحص وليست تشخيصاً مؤكداً.",
        "disease_weak_support": "لا يمنح النموذج {plant} دعماً إجمالياً يُذكر. أقوى فئة لديه هي {overall_disease} على {overall_plant} ({overall_score}). وضمن فئات {plant}، أقرب نتيجة هي {disease} ({score})، لكن مطابقة المحصول ضعيفة ولا تثبت أن الورقة سليمة أو مصابة.",
        "disease_class_score": "درجة الفئة ضمن المحصول المختار",
        "disease_crop_support": "دعم النموذج الإجمالي للمحصول",
        "disease_score_note": "تُرتب درجة الفئة ضمن فئات المحصول المختار، ويجمع دعم المحصول تلك الفئات عبر النموذج كله. لا تمثل أي من الدرجتين تشخيصاً مؤكداً.",
        "disease_weak_treatment": "لا توجد توصية علاجية لأن النموذج لم يطابق المحصول المختار بثقة. التقط صورة واضحة أخرى واستشر الإرشاد الزراعي المحلي قبل العلاج.",
    },
    "zh": {
        "disease_result": "在 {plant} 类别中，模型最接近的类别是 {disease}（{score}）。模型对 {plant} 的总体支持度为 {crop_support}。这是筛查结果，不是确诊。",
        "disease_weak_support": "模型对 {plant} 的总体支持度极低。模型最强的总体类别是 {overall_plant} 的 {overall_disease}（{overall_score}）。在 {plant} 类别中，最接近的是 {disease}（{score}），但作物匹配太弱，无法判断叶片健康或患病。",
        "disease_class_score": "所选作物类别内的得分",
        "disease_crop_support": "模型对该作物的总体支持度",
        "disease_score_note": "类别得分是在所选作物的标签中排序；总体支持度是这些标签在整个模型中的概率之和。两者都不能确诊。",
        "disease_weak_treatment": "模型未能可靠匹配所选作物，因此不提供处理建议。请重新拍摄清晰照片，并在处理前咨询当地农业指导人员。",
    },
    "fr": {
        "disease_result": "Parmi les classes de {plant}, la classe la plus proche est {disease} ({score}). Le soutien global du modèle pour {plant} est de {crop_support}. Il s’agit d’un dépistage, pas d’un diagnostic confirmé.",
        "disease_weak_support": "Le modèle accorde très peu de soutien global à {plant}. Sa classe globale la plus forte est {overall_disease} sur {overall_plant} ({overall_score}). Parmi les classes de {plant}, la meilleure correspondance est {disease} ({score}), mais la correspondance de culture est trop faible pour conclure que la feuille est saine ou malade.",
        "disease_class_score": "Score parmi les classes de la culture choisie",
        "disease_crop_support": "Soutien global du modèle pour la culture",
        "disease_score_note": "Le score de classe est calculé parmi les étiquettes de la culture choisie. Le soutien global additionne ces étiquettes dans tout le modèle. Aucun des deux ne confirme un diagnostic.",
        "disease_weak_treatment": "Aucun traitement n’est proposé, car le modèle n’a pas reconnu la culture choisie de façon fiable. Reprenez une photo nette et consultez un service agricole local avant tout traitement.",
    },
    "ru": {
        "disease_result": "Среди классов культуры {plant} ближайший класс — {disease} ({score}). Общая поддержка модели для {plant} составляет {crop_support}. Это результат проверки, а не подтверждённый диагноз.",
        "disease_weak_support": "Модель почти не поддерживает вариант {plant}. Самый сильный общий класс — {overall_disease} на растении {overall_plant} ({overall_score}). Среди классов {plant} лучший результат — {disease} ({score}), но совпадение культуры слишком слабое, чтобы считать лист здоровым или больным.",
        "disease_class_score": "Оценка среди классов выбранной культуры",
        "disease_crop_support": "Общая поддержка культуры моделью",
        "disease_score_note": "Оценка класса ранжируется среди меток выбранной культуры. Общая поддержка суммирует эти метки по всей модели. Ни одна оценка не является диагнозом.",
        "disease_weak_treatment": "Совет по лечению не дан, потому что модель ненадёжно сопоставила выбранную культуру. Сделайте чёткое фото и обратитесь в местную аграрную службу перед обработкой.",
    },
    "es": {
        "disease_result": "Entre las clases de {plant}, la más cercana es {disease} ({score}). El apoyo general del modelo para {plant} es {crop_support}. Es una detección inicial, no un diagnóstico confirmado.",
        "disease_weak_support": "El modelo ofrece muy poco apoyo general para {plant}. Su clase general más fuerte es {overall_disease} en {overall_plant} ({overall_score}). Entre las clases de {plant}, la más cercana es {disease} ({score}), pero la coincidencia del cultivo es demasiado débil para decir si la hoja está sana o enferma.",
        "disease_class_score": "Puntuación entre las clases del cultivo elegido",
        "disease_crop_support": "Apoyo general del modelo para el cultivo",
        "disease_score_note": "La puntuación de clase se calcula entre las etiquetas del cultivo elegido. El apoyo general suma esas etiquetas dentro de todo el modelo. Ninguna puntuación confirma un diagnóstico.",
        "disease_weak_treatment": "No se sugiere un tratamiento porque el modelo no identificó el cultivo elegido de forma fiable. Toma otra foto clara y consulta asesoría agrícola local antes de tratarlo.",
    },
}


def t(key: str, language: str = "en") -> str:
    """Return a translated interface string, falling back to English."""
    code = language if language in TEXT else "en"
    return TEXT[code].get(
        key,
        EXTRA_TEXT[code].get(
            key,
            ASSISTANT_TEXT[code].get(
                key,
                VOICE_TEXT[code].get(
                    key,
                    TEXT["en"].get(
                        key,
                        EXTRA_TEXT["en"].get(
                            key,
                            ASSISTANT_TEXT["en"].get(
                                key, VOICE_TEXT["en"].get(key, key)
                            ),
                        ),
                    ),
                ),
            ),
        ),
    )
